@{
    RootModule        = 'HawkwardHybrid.psm1'
    ModuleVersion     = '11.3.0'
    GUID              = '9f0235b3-6a75-4f62-9bbd-3fc479a9b2bc'
    Author            = 'shahr'
    CompanyName       = 'Hawkward'
    Copyright         = '(c) 2026 shahr. All rights reserved.'
    Description       = 'Hawkward Hybrid local PowerShell ops toolkit.'
    PowerShellVersion = '7.0'
    FunctionsToExport = @(
        'Add-HawkMemory',
        'Build-HawkAIContextPacket',
        'Build-HawkAIMemoryContext',
        'ConvertTo-HawkMarkdownTable',
        'ConvertTo-HawkReportMarkdown',
        'Format-HawkMarkdownCell',
        'Format-HawkMemoryId',
        'Format-HawkMemorySnippet',
        'Format-HawkReportCell',
        'Get-HawkAdmin',
        'Get-HawkAIDataProfile',
        'Get-HawkAIIntent',
        'Get-HawkAIStatus',
        'Get-HawkApp',
        'Get-HawkAppLocation',
        'Get-HawkAudit',
        'Get-HawkBadFile',
        'Get-HawkBattery',
        'Get-HawkBootMap',
        'Get-HawkCert',
        'Get-HawkClipCheck',
        'Get-HawkCompressedDir',
        'Get-HawkDiskPressureAudit',
        'Get-HawkDisplay',
        'Get-HawkDnsBench',
        'Get-HawkDnsCache',
        'Get-HawkDriveHealth',
        'Get-HawkDriverAudit',
        'Get-HawkDump',
        'Get-HawkEnv',
        'Get-HawkEnvMap',
        'Get-HawkEstablished',
        'Get-HawkEventStormAudit',
        'Get-HawkFirewallAudit',
        'Get-HawkGhostPortAudit',
        'Get-HawkHealth',
        'Get-HawkHostsCheck',
        'Get-HawkHypervisor',
        'Get-HawkLicense',
        'Get-HawkLink',
        'Get-HawkLinkSpeed',
        'Get-HawkLock',
        'Get-HawkMemoryFile',
        'Get-HawkMemoryMap',
        'Get-HawkMemorySearchTerm',
        'Get-HawkNetCheck',
        'Get-HawkNetwork',
        'Get-HawkNetworkTriage',
        'Get-HawkPatchHistory',
        'Get-HawkPathAudit',
        'Get-HawkPortMap',
        'Get-HawkPower',
        'Get-HawkProject',
        'Get-HawkPromptGitSegment',
        'Get-HawkPromptText',
        'Get-HawkRamInfo',
        'Get-HawkRecent',
        'Get-HawkReportPath',
        'Get-HawkResourceMap',
        'Get-HawkScheduledTaskRiskAudit',
        'Get-HawkShare',
        'Get-HawkShield',
        'Get-HawkSourceQualityScore',
        'Get-HawkSparseFile',
        'Get-HawkSpec',
        'Get-HawkSuspiciousProcessAudit',
        'Get-HawkSystem',
        'Get-HawkTempCheck',
        'Get-HawkUptime',
        'Get-HawkWifi',
        'Import-HawkPrerequisite',
        'Initialize-HawkProfile',
        'Install-HawkPrerequisite',
        'Invoke-ExplorerHere',
        'Invoke-HawkAI',
        'Invoke-HawkCachedData',
        'Invoke-HawkChangeAudit',
        'Invoke-HawkComplianceCheck',
        'Invoke-HawkDailyOps',
        'Invoke-HawkNetworkDiagnostics',
        'Invoke-HawkProject',
        'Invoke-HawkSearch',
        'Invoke-HawkSecurityAudit',
        'Invoke-HawkSystemReview',
        'Invoke-HawkThreatHunt',
        'New-HawkReport',
        'Protect-HawkSensitiveText',
        'Read-HawkMemory',
        'Resolve-HawkDuckDuckGoHref',
        'Search-HawkMemory',
        'Set-HawkAliases',
        'Set-HawkPrompt',
        'Set-HawkReadLine',
        'Show-HawkDashboard',
        'Show-HawkManual',
        'Test-HawkInteractiveSession',
        'Test-HawkModulePublisher',
        'Test-HawkPromptInjection',
        'Update-HawkModule',
        'Update-HawkProfile',
        'Watch-HawkDashboard',
        'Write-HawkHeader',
        'Write-HawkReportTable'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
