@{
    RootModule        = 'PowershellOps.psm1'
    ModuleVersion     = '11.3.0'
    GUID              = '9f0235b3-6a75-4f62-9bbd-3fc479a9b2bc'
    Author            = 'Shahriar Haque Abir'
    CompanyName       = 'Shahriar Haque Abir'
    Copyright         = 'Copyright (c) 2026 Shahriar Haque Abir. All rights reserved.'
    Description       = 'PowershellOps: A high-performance local PowerShell SysOps utility suite for Windows.'
    PowerShellVersion = '7.0'
    FunctionsToExport = @(
        'Add-OpsMemory',
        'Build-OpsAIContextPacket',
        'Build-OpsAIMemoryContext',
        'ConvertTo-OpsMarkdownTable',
        'ConvertTo-OpsReportMarkdown',
        'Format-OpsMarkdownCell',
        'Format-OpsMemoryId',
        'Format-OpsMemorySnippet',
        'Format-OpsReportCell',
        'Get-OpsAdmin',
        'Get-OpsAIDataProfile',
        'Get-OpsAIIntent',
        'Get-OpsAIStatus',
        'Get-OpsApp',
        'Get-OpsAppLocation',
        'Get-OpsAudit',
        'Get-OpsBadFile',
        'Get-OpsBattery',
        'Get-OpsBootMap',
        'Get-OpsCert',
        'Get-OpsClipCheck',
        'Get-OpsCompressedDir',
        'Get-OpsDiskPressureAudit',
        'Get-OpsDisplay',
        'Get-OpsDnsBench',
        'Get-OpsDnsCache',
        'Get-OpsDriveHealth',
        'Get-OpsDriverAudit',
        'Get-OpsDump',
        'Get-OpsEnv',
        'Get-OpsEnvMap',
        'Get-OpsEstablished',
        'Get-OpsEventStormAudit',
        'Get-OpsFirewallAudit',
        'Get-OpsGhostPortAudit',
        'Get-OpsHealth',
        'Get-OpsHostsCheck',
        'Get-OpsHypervisor',
        'Get-OpsLicense',
        'Get-OpsLink',
        'Get-OpsLinkSpeed',
        'Get-OpsLock',
        'Get-OpsMemoryFile',
        'Get-OpsMemoryMap',
        'Get-OpsMemorySearchTerm',
        'Get-OpsNetCheck',
        'Get-OpsNetwork',
        'Get-OpsNetworkTriage',
        'Get-OpsPatchHistory',
        'Get-OpsPathAudit',
        'Get-OpsPortMap',
        'Get-OpsPower',
        'Get-OpsProject',
        'Get-OpsPromptGitSegment',
        'Get-OpsPromptText',
        'Get-OpsRamInfo',
        'Get-OpsRecent',
        'Get-OpsReportPath',
        'Get-OpsResourceMap',
        'Get-OpsScheduledTaskRiskAudit',
        'Get-OpsShare',
        'Get-OpsShield',
        'Get-OpsSourceQualityScore',
        'Get-OpsSparseFile',
        'Get-OpsSpec',
        'Get-OpsSuspiciousProcessAudit',
        'Get-OpsSystem',
        'Get-OpsTempCheck',
        'Get-OpsUptime',
        'Get-OpsWifi',
        'Import-OpsPrerequisite',
        'Initialize-OpsProfile',
        'Install-OpsPrerequisite',
        'Invoke-ExplorerHere',
        'Invoke-OpsAI',
        'Invoke-OpsCachedData',
        'Invoke-OpsChangeAudit',
        'Invoke-OpsComplianceCheck',
        'Invoke-OpsDailyOps',
        'Invoke-OpsNetworkDiagnostics',
        'Invoke-OpsProject',
        'Invoke-OpsSearch',
        'Invoke-OpsSecurityAudit',
        'Invoke-OpsSystemReview',
        'Invoke-OpsThreatHunt',
        'New-OpsReport',
        'Protect-OpsSensitiveText',
        'Read-OpsMemory',
        'Resolve-OpsDuckDuckGoHref',
        'Search-OpsMemory',
        'Set-OpsAliases',
        'Set-OpsPrompt',
        'Set-OpsReadLine',
        'Show-OpsDashboard',
        'Show-OpsManual',
        'Test-OpsInteractiveSession',
        'Test-OpsModulePublisher',
        'Test-OpsPromptInjection',
        'Update-OpsModule',
        'Update-OpsProfile',
        'Watch-OpsDashboard',
        'Write-OpsHeader',
        'Write-OpsReportTable'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}


